### ISSUE TITLE
issue mattia

### ISSUE THREAD

**Issue by NetRider** [MattiaCiolli/GoSoftairV2#6]
se metto riproponi evento la mappa della form non si vede e non mi ricarica l’immagine originale

**Comment by NetRider** [comment]
Quando confermi la creazione dell’annuncio non ci sono i link a partite e mercatino nella navbar

Il modal dentro al profilo “ultimi annunci inseriti” non si vede

**Comment by FedericaCaruso** [comment]
Quando confermi la creazione dell’annuncio non ci sono i link a partite e mercatino nella navbar

già fatto
